name: frontend_docx_resizer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1 # For making the API call
  file_picker: ^8.0.3 # To pick the .docx file
  universal_html: ^2.2.4 # To trigger the download in the browser

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
